apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: NodePort  # Use LoadBalancer if deploying on a cloud provider
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007  # Access via http://<Minikube-IP>:30007
